### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by griganton** [griganton/telepy#3]
Discuss support of 2.7 and 3.4 both.
Problems and workarounds:

1. ConfigParser in 2 vs. configparser in 3. 
Workaround: try import and catch ImportError 

2. Bytes in 3 vs. unicode strings in 2.
Any ideas?

**Comment by awesomebytes** [comment]
1) Workaround done and tested here:

https://github.com/awesomebytes/telepy/blob/master/testing.py#L5-L9
```python
# Deal with py2 and py3 differences
try:
    import configparser
except ImportError:
    import ConfigParser as configparser
```

2) Some initial stuff done here:

https://github.com/awesomebytes/telepy/blob/master/mtproto.py#L14-L84

BytesIO getvalue() in Py2 does not return a `bytearray`, it returns a `str`, by overriding the method by adding that cast it works (mostly...).
```python
    from io import BytesIO

    # Override getvalue to force conversion to bytearray in python 2.X
    class BytesIO(BytesIO):
        def getvalue(self):
            return bytearray(super(BytesIO, self).getvalue())
```
As python2.7 has no `int().to_bytes()` method, I changed the calls to `int2bytes`, same thing with the inverse method. And for both versions of python the call is just bytes2int or int2bytes.
Python 2.7:
```python
    def bytes2int(in_str, endianess='little'):
        if endianess == 'big':
            tmp_str = bytearray(in_str)
            tmp_str.reverse()
            in_str = str(tmp_str)
        return int(in_str.encode('hex'), 16)
    def int2bytes(val, num_bytes):
        return bytearray([(val & (0xff << pos*8)) >> pos*8 for pos in range(num_bytes)])
```
Python 3.4:
```python
    def bytes2int(str, endianess='little'):
        return int.from_bytes(str, endianess)
    def int2bytes(val, num_bytes):
        return val.to_bytes(num_bytes, 'little')
```
Note that this is not completely working...

Also on visualization of data:
https://github.com/awesomebytes/telepy/blob/master/mtproto.py#L93

This makes not crash the `vis` function.

While working on `testing.py` I still have some problems to fix:

This assert always fails, because I changed the return type from who calls this, so it's kind of normal:
https://github.com/awesomebytes/telepy/blob/master/mtproto.py#L164-L166
```python
    def deserialize(self, bytes_io, type_=None, subtype=None):
        # This assert always fails py2
        #assert isinstance(bytes_io, BytesIO)
```

Then, just to make `testing.py` not crash I needed to add this:
```python
            if (2, 7, 0) <= version_info < (3, 0, 0):
                count = bytes2int(bytes_io.read(1))
            else:
                count = bytes2int(bytes_io.read(4))
```
It's ugly, and I don't really know what is going on. It will most probably fail on a general case.

On the timestamp needed here:
https://github.com/awesomebytes/telepy/blob/master/mtproto.py#L254-L255

I changed how to generate it (as the method .timestamp() that was before, does not exist in py2.7). Note that this does not behave equal, is not giving back UTC time...
```python
        # to make it work in py2 and py3 (py3 has the timestamp() method but py2 doesnt)
        curr_timestamp = (datetime.utcfromtimestamp(time()) - datetime(1970, 1, 1)).total_seconds()
```

And most probably the worst problem is here:
https://github.com/awesomebytes/telepy/blob/master/mtproto.py#L281-L283
```python
        # struct.error: integer out of range for 'L' format code
        # sometimes happens in py2
        step2 = step1 + struct.pack('<L', crc32(step1))
```

**Comment by griganton** [comment]
And most probably the worst problem is here:
https://github.com/awesomebytes/telepy/blob/master/mtproto.py#L281-L283
```python
        # struct.error: integer out of range for 'L' format code
        # sometimes happens in py2
        step2 = step1 + struct.pack('<L', crc32(step1))
```

**Please try to replace L by Q**. I have an idea that long (L) in 32 bit system is only 4 bytes, instead of 8 in 64 bit.

**Comment by awesomebytes** [comment]
@griganton I tried with Q, and It failed:
    struct.error: integer out of range for 'Q' format code
Kind of the same error, but when it didn't fail, existing code broke.

**Comment by awesomebytes** [comment]
I'm closing this, as we got something working on both version right now. If little issues appear, we can open a new one
